apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: failed-deployments
  namespace: monitoring
  labels:
    app: failed-deployments
spec:
  releaseName: failed-deployments
  chart:
    spec:
      chart: job
      sourceRef:
        kind: GitRepository
        name: chart-job
        namespace: flux-system
      interval: 1m
  interval: 5m
  values:
    schedule: "0 9 * * 1-5" # interval 9:00am Monday to Friday
    disableActiveClusterCheck: true
    concurrencyPolicy: "Forbid"
    failedJobsHistoryLimit: 3
    startingDeadlineSeconds: 300
    successfulJobsHistoryLimit: 3
    backoffLimit: 3
    restartPolicy: Never
    runAsRoot: true
    kind: CronJob
    image: hmctspublic.azurecr.io/failed-deployments:latest #{"$imagepolicy": "flux-system:failed-deployments"}
    imagePullPolicy: Always
    environment:
      CLUSTER_NAME: "cft-00-aks"
      ARTIFACT_URL: "http://source-controller.flux-system.svc.cluster.local."
      API_SERVER_URL: "https://kubernetes.default.svc.cluster.local"
    secrets:
      SLACK_WEBHOOK:
        secretRef: helm-base-versions
        key: slack-webhook
    nodeSelector:
      agentpool: linux
    tolerations:
      - key: dedicated
        effect: NoSchedule
        operator: Equal
        value: jobs


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: failed-deployments-sa
  namespace: monitoring

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: failed-deployments-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: failed-deployments-clusterrole
subjects:
  - kind: ServiceAccount
    name: failed-deployments-sa
    namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: failed-deployments-clusterrole
rules:
  - apiGroups: ['']
    resources: ['namespaces']
    verbs: ['list', 'get']
  - apiGroups: ['source.toolkit.fluxcd.io']
    resources: ['helmcharts']
    verbs: ['list', 'get']
  - apiGroups: ['apps']
    resources: ['deployments']
    verbs: ['list', 'get']
