apiVersion: batch/v1
kind: Job
metadata:
  name: helm-chart-base-versions
  namespace: monitoring
  labels:
    app: helm-chart-base-versions
spec:
  template:
    metadata:
      labels:
        app: helm-chart-base-versions
    spec:
        restartPolicy: Never
        serviceAccountName: helm-chart-base-versions-sa
        containers:
        - name: helm-chart-base-versions
          image: hmctspublic.azurecr.io/helm-base-versions:latest
          imagePullPolicy: Always
          env:
            - name: CLUSTER_NAME
              value: "cft-00-aks"
            - name: COSMOS_KEY
              value: "<your key in here>"
            - name: ARTIFACT_URL
              value: "http://source-controller.flux-system.svc.cluster.local."
            - name: API_SERVER_URL
              value: "https://kubernetes.default.svc.cluster.local"
  backoffLimit: 1

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-chart-base-versions-sa
  namespace: monitoring

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-chart-base-versions-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-chart-base-versions-clusterrole
subjects:
  - kind: ServiceAccount
    name: helm-chart-base-versions-sa
    namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-chart-base-versions-clusterrole
rules:
  - apiGroups: ['']
    resources: ['namespaces']
    verbs: ['list', 'get']
  - apiGroups: ['source.toolkit.fluxcd.io']
    resources: ['helmcharts']
    verbs: ['list', 'get']